<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[http://apis.juhe.cn/ip/ip2addr?ip=112.112.11.1&key=6e224eb7e17d305a9fdc22a3bcb8bc68]]>
    </line>
    <line>
      <![CDATA[响应数据：{"resultcode":"200","reason":"Return Successd!","result":{"area":"云南省昆明市","location":"电信"},"error_code":0}]]>
    </line>
    <line>
      <![CDATA[模板数据{"resultcode":"200"}]]>
    </line>
    <line>
      <![CDATA[测试通过]]>
    </line>
    <line>
      <![CDATA[http://apis.juhe.cn/ip/ip2addr?ip=110.112.11.1&key=6e224eb7e17d305a9fdc22a3bcb8bc68]]>
    </line>
    <line>
      <![CDATA[{"resultcode":"200","reason":"Return Successd!","result":{"area":"黑龙江省齐齐哈尔市","location":"中移铁通"},"error_code":0}]]>
    </line>
    <line>
      <![CDATA[模板数据{"resultcode":"200","reason":"Return Successd!","result":{"area":"黑龙江省齐齐哈尔市","location":"中移铁通"},"error_code":80}]]>
    </line>
    <line>
      <![CDATA[异常响应：Json值不正确，实际值是:0,期望值是:80]]>
    </line>
  </reporter-output>
  <suite name="Command line suite" duration-ms="1959" started-at="2019-01-16T08:48:11Z" finished-at="2019-01-16T08:48:13Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="1959" started-at="2019-01-16T08:48:11Z" finished-at="2019-01-16T08:48:13Z">
      <class name="parameter.TestService">
        <test-method status="PASS" signature="test0()[pri:0, instance:parameter.TestService@7823a2f9]" name="test0" duration-ms="1583" started-at="2019-01-16T16:48:11Z" finished-at="2019-01-16T16:48:13Z">
          <reporter-output>
            <line>
              <![CDATA[http://apis.juhe.cn/ip/ip2addr?ip=112.112.11.1&key=6e224eb7e17d305a9fdc22a3bcb8bc68]]>
            </line>
            <line>
              <![CDATA[响应数据：{"resultcode":"200","reason":"Return Successd!","result":{"area":"云南省昆明市","location":"电信"},"error_code":0}]]>
            </line>
            <line>
              <![CDATA[模板数据{"resultcode":"200"}]]>
            </line>
            <line>
              <![CDATA[测试通过]]>
            </line>
          </reporter-output>
        </test-method> <!-- test0 -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:parameter.TestService@7823a2f9]" name="test1" duration-ms="299" started-at="2019-01-16T16:48:13Z" finished-at="2019-01-16T16:48:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at parameter.TestService.test1(TestService.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at parameter.maintest.main(maintest.java:12)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[http://apis.juhe.cn/ip/ip2addr?ip=110.112.11.1&key=6e224eb7e17d305a9fdc22a3bcb8bc68]]>
            </line>
            <line>
              <![CDATA[{"resultcode":"200","reason":"Return Successd!","result":{"area":"黑龙江省齐齐哈尔市","location":"中移铁通"},"error_code":0}]]>
            </line>
            <line>
              <![CDATA[模板数据{"resultcode":"200","reason":"Return Successd!","result":{"area":"黑龙江省齐齐哈尔市","location":"中移铁通"},"error_code":80}]]>
            </line>
            <line>
              <![CDATA[异常响应：Json值不正确，实际值是:0,期望值是:80]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- parameter.TestService -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
